[project]
name = "mit-15-376-homework-3"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "click>=8.3.0",
    "gitpython>=3.1.45",
    "mcp>=1.15.0",
    "pydantic>=2.11.9",
]
